on:
  - push

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
    - run: gem update --system

    - env:
        GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
      run: |
        VERSION=$(ruby -e "puts eval(File.read('govuk_markdown.gemspec')).version")
        GEM_VERSION=$(gem list --exact --remote govuk_markdown)
        if [ "${GEM_VERSION}" != "govuk_markdown (${VERSION})" ]; then
          gem build govuk_markdown.gemspec
          gem push "govuk_markdown-${VERSION}.gem"
        fi
        if ! git ls-remote --tags --exit-code origin v${VERSION}; then
          git tag v${VERSION}
          git push --tags
        fi
