on:
  - push

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
    - run: gem update --system

    - env:
        GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
      run: |
        CURRENT_VERSION=$(rake gem_version)
        PUBLISHED_GEM_VERSION=$(gem list --exact --remote govuk_markdown)

        if [ "${PUBLISHED_GEM_VERSION}" != "govuk_markdown (${CURRENT_VERSION})" ]; then
          gem build govuk_markdown.gemspec
          gem push "govuk_markdown-${VERSION}.gem"
        fi
        if ! git ls-remote --tags --exit-code origin v${CURRENT_VERSION}; then
          git tag v${CURRENT_VERSION}
          git push --tags
        fi
