on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
    - name: Install dependencies
      run: gem update --system

    - env:
        GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
      name: Push a new gem version to Rubygems
      run: |
        echo "It works" > something.txt
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git commit -am "OK, and a commit works"
        git push
