name: Ruby
on:
  - pull_request
jobs:
  rspec:
    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.1.4', '3.2.3', '3.3.0']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - name: Install dependencies
      run: bundle install --jobs 4 --retry 3

    - name: Run linter
      run: bundle exec rubocop .

    - name: Run tests
      run: bundle exec rake
